回答:
1. 张量之间的 + , -, * , / 如何运算，有什么性质？
2. 什么是降维？为什么需要降维？如何计算？一个张量按照某一行降维后的结果是什么？在Pytorch中如何计算
3. 向量点积, 矩阵-向量积, 矩阵-矩阵积的含义？如何计算？在Pytorch中如何计算？
4. 什么是范式，举例并解释常用范式的计算, 在DL中的应用场景, 在Pytorch中如何计算？

In [2]:
import torch

### Basic Properties of Tensor Arithmetic
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B, A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [4]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [5]:
### Reduction
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [6]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [8]:
A_sum_axis0 = A.sum(dim=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [9]:
A_sum_axis1 = A.sum(dim=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [10]:
A.sum(dim=[0, 1])

tensor(190.)

In [11]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [14]:
A.mean(dim=0), A.sum(dim=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [17]:
#### Non-Reduction Sum
sum_A = A.sum(dim=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [18]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [19]:
A.cumsum(dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [21]:
### Dot Products
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [22]:
torch.sum(x * y)

tensor(6.)

In [25]:
### Matrix–Vector Products
A, x, A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [26]:
### Matrix–Matrix Multiplication
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [28]:
### Norms
u = torch.tensor([3.0, -4.0])
l2 = u.norm()
l2

tensor(5.)

In [30]:
l1 = torch.abs(u).sum()
l1

tensor(7.)

In [32]:
lf = torch.norm(torch.ones(4, 9))
lf

tensor(6.)

In [39]:
### homework
A = torch.arange(24).reshape(2, 3, 4)
len(A)

2

In [40]:
A = torch.arange(24).reshape(4, 6)
A.sum(dim=0), A.sum(dim=1), A / A.sum(dim=0)
# tensor A.sum(dim=1) at non-singleton dimension 

(tensor([36, 40, 44, 48, 52, 56]),
 tensor([ 15,  51,  87, 123]),
 tensor([[0.0000, 0.0250, 0.0455, 0.0625, 0.0769, 0.0893],
         [0.1667, 0.1750, 0.1818, 0.1875, 0.1923, 0.1964],
         [0.3333, 0.3250, 0.3182, 0.3125, 0.3077, 0.3036],
         [0.5000, 0.4750, 0.4545, 0.4375, 0.4231, 0.4107]]))

In [41]:
A = torch.ones(2, 3, 4)
A.sum(dim=0), A.sum(dim=1), A.sum(dim=2)

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]))

In [42]:
A = torch.ones(2, 3, 4)
torch.norm(A)

tensor(4.8990)

In [43]:
A = torch.ones(2, 3, 4, 5)
torch.norm(A)

tensor(10.9545)

In [49]:
torch.sqrt(torch.tensor([2*3*4*5]))

tensor([10.9545])

In [51]:
A = torch.tensor([[0, -2, 2], [5, 1, 5], [1, 4, -1]])
B = torch.arange(9).reshape(3, 3)
torch.mm(A, B)

tensor([[ 6,  6,  6],
        [33, 44, 55],
        [ 6, 10, 14]])