In [1]:
import sys
import os
sys.path.append(os.pardir)

import numpy as np
from common.functions import softmax, cross_entropy_error
from common.grad import numerical_gradient

class SimpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3) # 使用高斯分布进行初始化


    def predict(self, x):
        return np.dot(x, self.W)


    def loss(self, x, t):
        z = self.predict(x)
        p = softmax(z)
        loss = cross_entropy_error(p, t)
        return loss

net = SimpleNet()
net.W

array([[ 0.82523912, -0.30447998,  0.90931488],
       [ 0.04680012, -0.68667542,  1.43436369]])

In [2]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

net.predict(x), np.argmax(x), net.loss(x, t)

(array([ 0.53726359, -0.80069587,  1.83651625]), 1, 0.29587034840954873)

In [3]:
f = lambda w: net.loss(x, t)  # 伪函数
numerical_gradient(f, net.W)

array([[ 0.12173011,  0.03193961, -0.15366972],
       [ 0.18259516,  0.04790941, -0.23050458]])