In [4]:
import pandas as pd

data = pd.read_csv('data/house_tiny.csv')
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [21]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.select_dtypes(include='number').mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [22]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [34]:
import torch
# 
X, y = torch.tensor(inputs.to_numpy(dtype=float)), torch.tensor(outputs.to_numpy(dtype=float))  # 先转换为numpy.ndarray
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [102]:
homework_data = pd.read_csv('data/house_tiny.csv')
homework_data = homework_data.iloc[:, :-1]
cols = min(homework_data.count())
homework_data.drop(columns=homework_data.columns[cols])
homework_data = pd.get_dummies(homework_data, dummy_na=True)
homework_data = homework_data.fillna(0)
hw = torch.tensor(homework_data.to_numpy(dtype=int)[:, :-1])
hw

tensor([[0, 1],
        [2, 0],
        [4, 0],
        [0, 0]])