In [35]:
import torch

In [36]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [37]:
x.requires_grad_(True)  # 标识一个tensor是否需要在计算中保留梯度信息
x.grad

In [38]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [39]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [40]:
x.grad == 4 * x

tensor([True, True, True, True])

## Backward for Non-Scalar Variables

In [41]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [42]:
x.grad.zero_()
y = x * x
y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

## Detaching Computation

In [43]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [44]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

## Gradients and Python Control Flow

In [47]:
def f(a):
    b = a * 2
    while b.norm() < 1000: # L2范数是向量元素平方和的平方根
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [48]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [49]:
a.grad == d/a

tensor(True)

In [52]:
a.shape

torch.Size([])