In [1]:
import torch

In [4]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [5]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [12]:
a = torch.arange(4).reshape(2, 2, 1)
b = torch.arange(4).reshape(1, 2, 2)

a, b, a + b

(tensor([[[0],
          [1]],
 
         [[2],
          [3]]]),
 tensor([[[0, 1],
          [2, 3]]]),
 tensor([[[0, 1],
          [3, 4]],
 
         [[2, 3],
          [5, 6]]]))