In [16]:
import torch

In [17]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x.shape

torch.Size([12])

In [19]:
x.numel()

12

In [20]:
X = torch.reshape(x, shape=(3, 4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [21]:
X = torch.reshape(x, shape=(3, -1))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [22]:
X = torch.reshape(x, shape=(-1, 4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [24]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [28]:
torch.randn(size=(3, 4))

tensor([[ 0.4092,  0.6414, -0.2446, -0.4932],
        [-1.0799, -1.0385,  0.8183, -0.4123],
        [-1.1938,  0.8775, -2.3165,  1.2044]])

In [29]:
torch.tensor(data= [[1, 2, 3, 4], [5, 6, 7, 8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])