回答：
1. Scalars, Vector, Matrices, Tensor 的含义，数学符号，在Pytorch中如何创建？
2. Scalars -> Vector -> Matrices -> Tensor 直接的泛化关系
3. 轴的概念是什么？

In [2]:
import torch

In [3]:
### Scalar

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
### Vectors

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
print(len(x))
print(x.shape)

4
torch.Size([4])


In [8]:
### Matrices
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
A[1][2]

tensor(6)

In [10]:
#### transpose
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
#### symmetric matrix
B = torch.tensor([[1, 2, 3], 
                  [2, 0, 4], 
                  [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [14]:
### tensor
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])